---
- name: update chache 
  shell: sudo apt update 
- name: Install required packages
  apt: 
    name: bzip2 
    state: present



- name: Check if Anaconda is already installed
  stat:
    path: "{{ anaconda_install_path }}anaconda{{ anaconda_python_version }}"
  register: check_anaconda_install_path

- name: Download Anaconda
  shell: wget https://repo.continuum.io/archive/Anaconda3-2024.06-1-Linux-x86_64.sh -o /tmp/Anaconda3-2024.06-1-Linux-x86_64.sh
  # get_url:
  #   url: https://repo.continuum.io/archive/Anaconda3-2024.06-1-Linux-x86_64.sh
  #   dest: "/tmp/Anaconda{{ anaconda_python_version }}-{{ anaconda_version }}-Linux-x86_64.sh"
  #   mode: 0755
  when: not check_anaconda_install_path.stat.exists

- name: Install Anaconda

  shell: "/tmp/Anaconda3-2024.06-1-Linux-x86_64.sh -b -p {{ anaconda_install_path }}anaconda{{ anaconda_python_version }}"
  args:
    executable: /bin/bash
  register: anaconda_install
  when: not check_anaconda_install_path.stat.exists

- name: Add Anaconda to the system path in /etc/profile
  lineinfile:
    path: /etc/profile
    regexp: ^export PATH=.*anaconda.*
    line: "export PATH=\"{{ anaconda_install_path }}anaconda{{ anaconda_python_version }}/bin:$PATH\""
    backup: true
